version: "3.8"
services:
  hapi-server:
    container_name: hapi-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - hapi-network
    depends_on:
      - postgres-db
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - ${PORT}
    volumes:
      - ./logs:/hapi-server/logs
      - ./nodemon.json:/hapi-server/nodemon.json
    command: npm run dev
    restart: on-failure
  postgres-db:
    container_name: hapi-postgres-db
    build:
      context: ./postgres-database
      dockerfile: Dockerfile
    networks:
      - hapi-network
    ports:
      - ${POSTGRES_PORT}-${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: on-failure
networks:
  hapi-network:
    name: hapi-network
    driver: bridge
volumes:
  pgdata:
  logs:
