version: "3.8"
services: 
  postgres:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: "postgres"
    env_file:
      - .env
    networks:
      - rsschool
    environment: 
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: "app"
    depends_on:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
      - logs:/usr/src/app/logs
    restart: always
    env_file:
      - .env
    networks:
      - rsschool
networks:
  rsschool:
    driver: bridge

volumes:
  db:
  logs: